Merge feature/pdda 197 into master
hmcts/pdda-shared-infrastructure pull request #43
Opened 2024-02-13 10:32 UTC by gittinsl

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-02-14 13:52 UTC, AnasGhafouri1 requested changes

2024-02-14 14:08 UTC, gittinsl commented on src/main/java/uk/gov/hmcts/pdda/business/entities/PddaEntityHelper.java
> -            LOG.error("Initial SessionFactory creation failed." + ex);
When catching exceptions, if there's a log line right after sonarqube complains: "_Exceptions should be either logged or rethrown but not both_". So to make sure there's no sonar issues I've removed this log line.

2024-02-14 14:13 UTC, gittinsl commented on src/main/java/uk/gov/hmcts/pdda/web/publicdisplay/rendering/compiled/DocumentUtils.java
> -
The method was unused, I'd checked using Eclipse's References -> in workspace and nothing used it, so I've removed it.

2024-02-14 14:15 UTC, gittinsl commented on src/main/java/uk/gov/hmcts/pdda/business/services/formatting/FormattingServicesProcessing.java
> -            LOG.error(MERGING_ERROR + val.getCppFormattingId() + ":" + ex.getMessage());
The removal of this log line is for the same reason as the PddaEntityHelper one. So that sonar passes.

2024-02-14 15:24 UTC, gittinsl commented on src/test/java/uk/gov/hmcts/pdda/business/services/formatting/FormattingServicesFormattingExceptionsTest.java
> +        static final String PDDA_AND_XHIBIT = "2";
Removed

2024-02-14 15:56 UTC, gittinsl commented on src/test/java/uk/gov/hmcts/pdda/business/services/formatting/FormattingServicesFormattingExceptionsTest.java
> +        XhbClobDao xhbClobDao = DummyFormattingUtil.getXhbClobDao(Long.valueOf(1), CPP_LIST);
Extracted the initialisation of XhbCppListDao into its own method.

2024-02-16 13:56 UTC, AnasGhafouri1 approved these changes

2024-02-16 13:57 UTC, merged